@startuml
skinparam backgroundcolor #fff/aaf
skinparam shadowing 1
footer ©2025 Sean Donnellan
title Subsection 1 (Section 2) Diagram
start
:Subsection 1 Action;
:Process subsection content;
stop
@enduml