= Example Asciidoc Document
:toc: right
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:title-page:
:data-uri:
:allow-uri-read: true
:doctype: book
:book-flag: true
:localdir: ./
:imagesdir: {localdir}
:source-highlighter: rouge
:icons: font
:!reproducible:
:pdf-page-size: A4
:pdf-stylesdir: lib/themes
:pdf-style: VSR-theme.yml
:pdf-fontsdir: lib/fonts
:listing-caption: Listing
:favicon: ./lib/favicon.ico
:classification: Virtual Space and Global Communications Research Confidential
:title-logo-image: image:./chapter-logo/VSR-logo-space.svg[pdfwidth=2.5in,align=right]

[#Chapter-example-chapter]
include::./chapter-example/chapter-example.asciidoc[leveloffset=+1]

[#Chapter-logo-chapter]
include::./chapter-logo/chapter-logo.asciidoc[leveloffset=+1]

[#Chapter-examplelinks-chapter]
== Example external links to other material
.github link to an jupyter notebook of an example 3d Object
link:https://github.com/donnels/3d-objects/blob/main/spoolholder.ipynb[^]

The above is an example of dockerizing Jupyter while adding an openscad kernel to be able to describe the story of how an object was created. The jupyter notebook seen above is the static output of the interactive Jupyter notebook that was created and edited in a dokerized environment. The .ipynb is an extension assigned to jupyter notebooks and the kernel for openscad was added for a Raspberry Pi (ARM CPU) by Sean Donnellan so as to give jupyter a home there in the VSR network. Normally Jupyter is used with Python or R for example for data analysis while mixing code and documentation. Output can also be PDF. When opened in the proper Jupyter environment, online web based editor, it is interactive.

.The object created for printing
link:https://github.com/donnels/3d-objects/blob/main/spool.stl[^]

.A link to some ARM software for IOT created before the Raspberry Pi
link:https://www.auto.tuwien.ac.at/~mkoegler/index.php/eibnslu[^]

The above was created by Sean because he saw the potential of the Arm platform for IoT and began exploring it before the Raspberry Pi existed and before the Iphone existed.

image::https://github.com/donnels/openscad-examples/actions/workflows/adoc.yml/badge.svg[badge]            

.status table    
|===
image::https://github.com/donnels/openscad-examples/actions/workflows/adoc.yml/badge.svg[badge]
|===

[appendix]
[#Chapter-Glossary]
== Glossary
include::./book-glossary.adoc[leveloffset=+1]

[appendix]
[#Chapter-Notation]
include::./book-notation.adoc[leveloffset=+1]

[#Copyright]
include::./book-copyright.adoc[leveloffset=+1]