@startuml
title Example with logo
footer Author Sean Donnellan
skinparam LegendBackgroundColor #aaf/fff
skinparam LegendBorderColor #aaf/fff
skinparam BackgroundColor #fff/aaf

legend
legend goes here.. can contain colour also.
end legend

card "<font color=#ffffff>Virtual Space Research</font>" as logoWithBack #ff462d

card "<font color=#ff462d>Virtual Space Reserach</font>" as LogolOrangeFontCol #ffffff

@enduml