:@startuml
title Customer OOB access in DC
footer (C)2021 Sean Donnellan
header <font color=red>DRAFT</font>
skinparam BackgroundColor #fff/aaf
skinparam ArrowColor #black
skinparam UsecaseBackgroundColor #aaf
skinparam UsecaseBorderColor #black
skinparam LegendBackgroundColor #aaf/fff
legend left
| Color | Type |
|<#orange>| OOB equip |
|<#red>| Service related equipment|
Author Sean Donnellan
Created 2021
endlegend
rectangle DCS {
    cloud client{
        card router #red
        card switch #red
        card oobswitch #orange
        card oobrtr #orange
        card vpnfw #orange
        card LPAR #red
        LPAR - switch :service
        switch - router :service
        oobswitch -- switch :OOB-LAN \n<100m
        oobswitch -- router :OOB-LAN \n<100m
        oobrtr -. switch :OOB-SER \n<20m
        oobrtr -. router :OOB-SER \n<20m
        vpnfw -- oobrtr
        vpnfw -- oobswitch
    }
}
cloud internet #orange
cloud ClientPremise #red
actor clientAdmin
cloud LTE #orange
router - ClientPremise : WAN
vpnfw - internet :GNPP?
internet <- clientAdmin :VPN
switch -. LTE :Wireless
router -. LTE :Wireless
note right of LTE
Most Data centres have issues with LTE.
Site survey required before use.
endnote
@enduml